### ISSUE TITLE
Required cmake modules are missing from source tarball

### ISSUE THREAD

**Issue by plaes** [open-eid/libdigidoc#3]
In the source tarball of 3.10.1 the `cmake` directory is empty causing build to fail:

```
CMake Error at CMakeLists.txt:12 (include):
  include could not find load file:

    VersionInfo
```

Is this intentional (packagers for other distros should take those files from open-eid/cmake repo) or oversight?

**Comment by plaes** [comment]
I had to copy at least following to get it compiling on Gentoo:
- FindIconv.cmake
- FindPKCS11.cmake
- VersionInfo.cmake

**Comment by metsma** [comment]
Github does not add submodules to zip/tar.gz output.
For quick fix you can download debian orig.tar.gz output.
I will look how to create tar output with travis

**Comment by plaes** [comment]
Ok, didn't know it was github's issue.

I looked into libdigidoc_3.10.1.1208.orig.tar.xz which includes contents of extra directories, but also contains full `.git` directory for submodules.

PS. It would be also nice for files inside tarball to have package-version/ prefix (like the github-generated ones have).

**Comment by metsma** [comment]
Travis creates now tar.gz for each tag release
