### ISSUE TITLE
Build errors with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by andrewshadura** [open-eid/libdigidoc#4]
Hi,

As reported by Kurt Roeckx (@kroeckx), libdigidoc fails to build from source against OpenSSL 1.1.0, which is about to be released. Logs can be found here: https://breakpoint.cc/openssl-1.1-rebuild-2016-05-29/Attempted/libdigidoc_3.10.1.1208+ds1-2_amd64-20160529-1440

See https://wiki.openssl.org/index.php/1.1_API_Changes to find a possible reason for it to fail.

(Originally reported as [Debian bug #828391](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828391).)

**Comment by andrewshadura** [comment]
Hi, any updates on this one?

**Comment by Germano0** [comment]
It is important to implement OpenSSL 1.1 support because on certain Linux distributions, [compatibility OpenSSL 1.0 library conflicts with OpenSSL 1.1](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/6ZAMXPQFROMKM7ZX2JDLH3HA46KJY3GJ/)
